version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.8.2

jobs:
  build_and_deploy:
    environment:
      IMAGE_NAME: nayoakinyele/node-aws-docker
    executor: python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and tag 'node-aws-docker' docker image
          command: docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Push to dockerhub
          command: docker push $IMAGE_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
